---
- name: create mongodb directory
  file:
    path: files/{{ mongodb_project_dir }}/mongodb
    state: directory
  delegate_to: localhost
  run_once: true
  become: no
  tags:
  - never

- name: generate cfssl config files
  template:
    src: "{{ item }}.j2"
    dest: files/{{ mongodb_project_dir }}/mongodb/{{ item }}
  with_items:
  - ca.json
  - server.json
  - mongodb.json
  delegate_to: localhost
  run_once: true
  become: no
  tags:
  - never

- name: generate mongodb certificates
  shell: |
    set -o pipefail \
    && cfssl gencert -initca ca.json | cfssljson -bare mongodb-ca \
    && cfssl gencert -ca mongodb-ca.pem -ca-key mongodb-ca-key.pem \
    -config server.json -profile=server mongodb.json | cfssljson -bare mongodb \
    && cat mongodb-key.pem mongodb.pem > .mongo-pki_keypair.pem
  environment:
    ANSIBLE_MONGODB_WORKDIR: files/{{ mongodb_project_dir }}/mongodb
  args:
    chdir: $ANSIBLE_MONGODB_WORKDIR
  delegate_to: localhost
  run_once: true
  become: no
  tags:
  - never
